################################### Catalan language #####################################
[ca]
languageName = "Ca"
languageCode = "ca-ES"
contentDir = "content/catalan"
weight = 1
# footer content
[ca.params]
footer_content = "que el dolor sigui gran, que la trista elitr s'arregla, però el nonumy diam llargament envegen, com amb el treball i el dolor era gran per alguns, però el plaer del diam."


################################### English language #####################################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# footer content
[en.params]
footer_content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."
